DROP DATABASE IF EXISTS LADATA_DB;
CREATE DATABASE LADATA_DB;
USE LADATA_DB;
CREATE TABLE `LADATA_DB`.`la_crimes_rate` (
  `DR Number` int(11) NOT NULL,
  `Date_Reported` varchar(45) DEFAULT NULL,
  `Date_Occurred` varchar(45) DEFAULT NULL,
  `Time_Occurred` varchar(45) DEFAULT NULL,
  `Area_ID` varchar(45) DEFAULT NULL,
  `Area_Name` varchar(45) DEFAULT NULL,
  `Reporting_District` varchar(45) DEFAULT NULL,
  `Crime_Code` varchar(45) DEFAULT NULL,
  `Crime_Code_Description` varchar(45) DEFAULT NULL,
  `MO_Codes` varchar(45) DEFAULT NULL,
  `Victim_Age` varchar(45) DEFAULT NULL,
  `Victim_Sex` varchar(45) DEFAULT NULL,
  `Victim_Descent` varchar(45) DEFAULT NULL,
  `Premise_Code` varchar(45) DEFAULT NULL,
  `Premise_Description` varchar(45) DEFAULT NULL,
  `Weapon_Used_Code` varchar(45) DEFAULT NULL,
  `Weapon_Description` varchar(45) DEFAULT NULL,
  `Status_Code` varchar(45) DEFAULT NULL,
  `Status_Description` varchar(45) DEFAULT NULL,
  `Crime Code_1` varchar(45) DEFAULT NULL,
  `Crime Code_2` varchar(45) DEFAULT NULL,
  `Crime Code_3` varchar(45) DEFAULT NULL,
  `Crime Code_4` varchar(45) DEFAULT NULL,
  `Address` varchar(45) DEFAULT NULL,
  `Cross_Street` varchar(45) DEFAULT NULL,
  `Location` varchar(45) DEFAULT NULL
);
CREATE TABLE `LADATA_DB`.`parking_citations` (
  `Ticket_number` INT NOT NULL,
  `Issue_Date` VARCHAR(45) NULL,
  `Issue_time` VARCHAR(45) NULL,
  `Meter Id` VARCHAR(45) NULL,
  `Marked_Time` VARCHAR(45) NULL,
  `RP State_Plate` VARCHAR(45) NULL,
  `Plate Expiry_Date` VARCHAR(45) NULL,
  `VIN` VARCHAR(45) NULL,
  `Make` VARCHAR(45) NULL,
  `Body_Style` VARCHAR(45) NULL,
  `Color` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  `Route` VARCHAR(45) NULL,
  `Agency` VARCHAR(45) NULL,
  `Violation_code` VARCHAR(45) NULL,
  `Violation_Description` VARCHAR(45) NULL,
  `Fine amount` VARCHAR(45) NULL,
  `Latitude` VARCHAR(45) NULL,
  `Longitude` VARCHAR(45) NULL,
  PRIMARY KEY (`Ticket_number`));
